# .github/release.yml

changelog:
  categories:
    - title: Bug Fixes 🛠
      labels:
        - bug
    - title: New Features 🎉
      labels:
        - feature-dev-code
    - title: UI Improvements 🪞
      labels:
        - UI
    - title: New Assets 🎨
      labels:
        - assets
    - title: Other Changes
      labels:
        - "*"
