name: generate-documentation
run-name: Generate Documentation for all JS files in source
on:
  workflow_call:

jobs:
  create-docs:
    runs-on: ubuntu-latest

    permissions:
      # Lets this job push the docs to the repository
      contents: write
    strategy:
      matrix:
        nodeversion: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Create documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source/pages
          recurse: true
          output_dir: ./docs
      - name: Add documentation to repository
        run: |
          git config --global user.email "kjp002@ucsd.edu"
          git config --global user.name "Khushi Patel"
          git add docs
          git commit -m "Updated docs"
          git push
