name: generate-documentation
run-name: Generate Documentation for all JS files in source
on:
  workflow_call:

jobs:
  create-docs:
    runs-on: ubuntu-latest

    permissions:
      # Lets this job push the docs to the repository
      contents: write
      # Lets this job run other jobs
      workflow: write
    strategy:
      matrix:
        nodeversion: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Delete old Docs
        run: rm -r ./docs*
      - name: Create documentation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source/pages
          recurse: true
          output_dir: ./docs
      - name: Add documentation to repository
        run: |
          git config --global user.email "kjp002@ucsd.edu"
          git config --global user.name "Khushi Patel"
          git add docs
          git commit -m "Updated docs"
          git push
      - name: Trigger formatter action
        uses: actions/github-script@v6
        with:
          script: |
            const workflow_ref = process.env.GITHUB_REF.split('/').pop();
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'formatter.yml',
              ref: workflow_ref,
            })
      - name: Trigger tests action
        uses: actions/github-script@v6
        with:
          script: |
            const workflow_ref = process.env.GITHUB_REF.split('/').pop();
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'tests.yml',
              ref: workflow_ref,
            })