name: generate-documentation
run-name: Generate Documentation for all JS files in source
on: #[push, pull_request] 
    workflow_call:

#jobs:
 # documentation:
  #  runs-on: ubuntu-latest

   # strategy:
    #    matrix:
     #     nodeversion: [16]

    #steps:
     # - uses: actions/checkout@v3
      #- name: Set up node
       # uses: actions/setup-node@v3
        #with:
         # node-version: ${{ matrix.nodeversion }}
    #  - name: Install JSDocs
     #   run: npm install -g jsdocs
     # - name: Run JSDocs
      #  run: jsdoc ./source

jobs:
    create-docs:
        runs-on: ubuntu-latest
        
        permissions:
          # Lets this job push the docs to the repository
          contents: write
        
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: Create documentation
            uses: andstor/jsdoc-action@v1
            with:
              source_dir: ./source/pages
              recurse: true
              output_dir: ./docs
          - name: Add documentation to repository
            run: |
              git add docs
              git commit -m "Updated docs"
              git push

              