name: Continuous Integration Tests

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nodeversion: [16]
        jestversion: [29.5]

    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: Install JSDocs
        run: npm install jsdocs
      - name: Install JEST
        run: npm install jest@${{ matrix.jestversion }}
      - name: Run tests
        run: $(npm bin)/jest